#######################################################################################################
# Описание:
# Кастомный конфиг с использованием RU Zone согласно спискам https://github.com/hydraponique/roscomvpn-routing
# Конфиг для роутеров Keenetic + xKeen Mihomo + Zashboard
# Веб-интерфейс доступен по адресу http://192.168.1.1:9090/ui (192.168.1.1 = IP роутера). 
# После добавления сервера и запуска mihomo необходимо зайти в веб-интерфейс и выбрать нужное подключение для селекторов.
# Группа "GLOBAL VPN" определяет куда (на какой сервер) будет отправляться трафик, который не переопределенным иными правилами.
# Остальные группы имеют приоритет над группой "GLOBAL VPN" для переопределения (например, YouTube должен быть выше чем Google).
#######################################################################################################
# Для работы Discord требуется проксировать порты XKeen: 80,443,2000:2300,8443,19200:19400,50000:50030
# Для работы Whatsapp/Telegram требуется проксировать порты Xkeen: 80,443,596:599,1400,3478,5222
# Не забываем прописать IP своего сервера в /etc/xkeen/ip_exclude.lst
#######################################################################################################
redir-port: 1182 #Если нужен только режим Tproxy, то следует удалить данный порт
tproxy-port: 1181
log-level: silent
allow-lan: true
mode: rule
find-process-mode: off
tcp-concurrent: true
unified-delay: true
external-controller: 0.0.0.0:9090
external-ui: ./zash
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip

profile:
  store-selected: true

sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP: 
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]

# Использование VLESS подключения (НЕ ПОДПИСКА). Удалить или заполнить данный блок.
proxies:

  - name: *Name vless connection*
    type: vless
    server: *your-server*
    port: 443
    network: tcp
    udp: true
    tls: true
    packet-encoding: xudp
    servername: *your-sni*
    client-fingerprint: chrome
    uuid: *your-uuid*
    flow: xtls-rprx-vision
    reality-opts:
      public-key: *your-public-key*
      short-id: *your-shortid*

# Провайдеры VPN (подписка). Удалить или заполнить данный блок.
proxy-providers:

  *Name proxy service*:
    type: http
    url: *url from proxy service*
    path: ./proxy-providers/*name of proxy service*.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
      expected-status: 204

# Селекторы
proxy-groups:
  - name: GLOBAL VPN
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png
    include-all: true
    proxies: [DIRECT,Fastest,Fallback]

  - name: Fastest
    type: url-test
    hidden: false
    url: https://www.gstatic.com/generate_204
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png
    interval: 300
    max-failed-times: 3
    include-all: true
    exclude-filter: "LTE|Обход|Белые|Белых|Russia|Россия" # Исключаем сервера для обхода БС

  - name: Fallback
    type: fallback
    url: https://www.gstatic.com/generate_204
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png
    interval: 300
    max-failed-times: 3
    include-all: true
    exclude-filter: "LTE|Обход|Белые|Белых|Russia|Россия" # Исключаем сервера для обхода БС

  - name: Other
    type: select
    icon: https://www.svgrepo.com/show/12922/growth.svg
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

# Блокировка рекламы
  - name: Adblock
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    include-all: false
    proxies: [DIRECT, REJECT-DROP, PASS]

# RU, BY, KZ зона
  - name: RU Zone
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Russia.png
    include-all: false
    proxies: [DIRECT]

# Выборочные сервисы
  - name: Apple
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Apple.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Google Play
    type: select
    icon: https://www.svgrepo.com/show/353828/google-play-icon.svg
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Github
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Microsoft
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Reddit
    type: select
    icon: https://www.svgrepo.com/show/452094/reddit.svg
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Twitch (FIX Best Quality)
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

# Игровые сервисы
  - name: Steam
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Steam.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Origin
    type: select
    icon: https://www.svgrepo.com/show/354154/origin.svg
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]

  - name: Epic Games
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Epic_Games.png
    include-all: true
    proxies: [DIRECT,GLOBAL VPN]
    
# Правила маршрутизации
rule-anchors:
  domain: &domain { type: http, format: mrs, behavior: domain, interval: 86400, proxy: Fallback }
  ip: &ipcidr { type: http, format: mrs, behavior: ipcidr, interval: 86400, proxy: Fallback }
  ip-text: &ipcidr-text { type: http, format: text, behavior: ipcidr, interval: 86400, proxy: Fallback }
  classical: &classical { type: http, format: text, behavior: classical, interval: 86400, proxy: Fallback }
  inline: &inline { type: inline, behavior: classical }

rule-providers:

  # RU зона
  geosite-ru: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/category-ru.mrs }
  geosite-whitelist: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/whitelist.mrs }
  geoip-ru: { <<: *ipcidr, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geoip/release/mihomo/direct.mrs }
  geoip-kz: { <<: *ipcidr, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geoip/kz.mrs }

  # Реклама
  adlist-geosite: { <<: *domain, url: https://github.com/zxc-rv/ad-filter/releases/latest/download/adlist.mrs }
  winspy-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/win-spy.mrs }

  # Выборочные сервисы
  apple-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/apple.mrs }
  microsoft-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/microsoft.mrs }
  telegram-geosite: { <<: *domain,url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/telegram.mrs }
  youtube-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/youtube.mrs }
  googleplay-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/google-play.mrs }
  github-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/github.mrs }
  reddit-geosite: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/reddit.mrs }
  spotify-geosite: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/spotify.mrs }
  twitchads-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/twitch-ads.mrs }
  twitch-geosite: { <<: *domain, url: https://cdn.jsdelivr.net/gh/hydraponique/roscomvpn-geosite/release/mihomo/twitch.mrs }

  # Игровые сервисы
  steam-geosite: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/steam.mrs }
  origin-geosite: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/origin.mrs }
  ea-geosite: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/ea.mrs }
  epicgames-geosite: { <<: *domain, url: https://github.com/MetaCubeX/meta-rules-dat/raw/meta/geo/geosite/epicgames.mrs }

  # Ручные списки в DIRECT
  direct-inline:
    type: inline
    behavior: classical
    payload: #Типы правил: https://wiki.metacubex.one/ru/config/rules/
      - DOMAIN-SUFFIX,kz
      - DOMAIN-SUFFIX,2ip.io #Мусорный сервис сотрудничащий с РФ
  
  # Ручные списки в VPN
  proxy-inline:
    type: inline
    behavior: classical
    payload: #Типы правил: https://wiki.metacubex.one/ru/config/rules/
      - DOMAIN-KEYWORD,rezka #Rezka.ag и любые ее проявления
      - DOMAIN-KEYWORD,voidboost #Rezka.ag CDN сервера с фильмами

# Правила
rules:
  # Блокировки в REJECT
  - AND,((NETWORK,udp),(DST-PORT,443)),REJECT-DROP #Блокировка QUIC
  - OR,((RULE-SET,adlist-geosite),(RULE-SET,winspy-geosite)),Adblock #Блокировка рекламы и Windows трекеров

  # Ручные списки в VPN
  - RULE-SET,proxy-inline,Other
  
  # Ручные списки в DIRECT
  - RULE-SET,direct-inline,DIRECT
  
  # Выборочные сервисы
  - RULE-SET,telegram-geosite,Telegram
  - RULE-SET,youtube-geosite,YouTube
  - RULE-SET,googleplay-geosite,Google Play
  - RULE-SET,github-geosite,Github
  - RULE-SET,spotify-geosite,Spotify
  - RULE-SET,twitchads-geosite,Twitch (FIX Best Quality) # Рекомендовано в PROXY (Фикс высокого качества)
  - RULE-SET,apple-geosite,Apple # Рекомендовано в DIRECT
  - RULE-SET,microsoft-geosite,Microsoft # Рекомендовано в DIRECT
  - RULE-SET,reddit-geosite,Reddit # Рекомендовано в DIRECT
  - RULE-SET,twitch-geosite,DIRECT # По умолчанию в DIRECT
  
  # Игровые сервисы
  - RULE-SET,steam-geosite,Steam
  - OR,((RULE-SET,origin-geosite),(RULE-SET,ea-geosite)),Origin
  - RULE-SET,epicgames-geosite,Epic Games

  # RU Zone
  - OR,((RULE-SET,geosite-ru)(RULE-SET,geosite-whitelist),(RULE-SET,geoip-ru),(RULE-SET,geoip-kz)),RU Zone

  # Остальной трафик
  - MATCH,GLOBAL VPN
